// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.EdIlyin.PowerShell")>]
[<assembly: AssemblyProductAttribute("FSharp.EdIlyin.PowerShell")>]
[<assembly: AssemblyDescriptionAttribute("combinable decoders for PowerShell objects")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.EdIlyin.PowerShell"
    let [<Literal>] AssemblyProduct = "FSharp.EdIlyin.PowerShell"
    let [<Literal>] AssemblyDescription = "combinable decoders for PowerShell objects"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
